#ifndef LIBSPIKE_FLASH_H
#define LIBSPIKE_FLASH_H

#include <stm32h7xx.h>

enum flash_latency {
    FLASH_LATENCY0 = FLASH_ACR_LATENCY_0WS,
    FLASH_LATENCY1 = FLASH_ACR_LATENCY_1WS,
    FLASH_LATENCY2 = FLASH_ACR_LATENCY_2WS,
    FLASH_LATENCY3 = FLASH_ACR_LATENCY_3WS,
    FLASH_LATENCY4 = FLASH_ACR_LATENCY_4WS,
    FLASH_LATENCY5 = FLASH_ACR_LATENCY_5WS,
    FLASH_LATENCY6 = FLASH_ACR_LATENCY_6WS,
    FLASH_LATENCY7 = FLASH_ACR_LATENCY_7WS
};

void flash_set_latency(enum flash_latency);

#endif /* LIBSPIKE_FLASH_H */
